ADR механизма выставления заявки
FizzyShow/markershtern pull request #10
Opened 2022-07-21 21:08 UTC by paradoxubivaet

2022-07-23 18:52 UTC, stictt commented on docs/OrderMechanism/ADR.md
> +Kafka в Микросервис товаров, доступных для торговли(общий список всех заявок на покупку/продажу).
Через gRPC т.е общение на прямую же ? Это вполне тянет на изменение состояния. А значит это можно посадить на событие. 
Но в таком случаи, не понятно Как мы получим ответ. 
Плюс заявки это не мгновенный обмен. Order может на покупку и продажу висеть, ему не нужно проверять, продает кто то товар сейчас или нет. Кто то будет продавать под нашу заявку на покупку, значит ордер будет закрыт.

2022-07-23 18:52 UTC, stictt commented on docs/OrderMechanism/ADR.md
> +Kafka в Микросервис товаров, доступных для торговли(общий список всех заявок на покупку/продажу).
Так же нужен где то механизм работающий в фоне, который создает цикличную обработку, подходят ли какие то ордера под продажу друг другу, или нет. 
Продажа не всегда может быть на событие открытие ордера. 
У нас с определенной периодичностью меняется система. И как только будет новые требования, на изменение Order, вся система станет не жизнеспособной, так как это не событие открытия заявки.

2022-07-23 19:52 UTC, paradoxubivaet commented on docs/OrderMechanism/ADR.md
> +Kafka в Микросервис товаров, доступных для торговли(общий список всех заявок на покупку/продажу).
Я не доделал

2022-07-23 19:52 UTC, paradoxubivaet commented on docs/OrderMechanism/ADR.md
> +Kafka в Микросервис товаров, доступных для торговли(общий список всех заявок на покупку/продажу).
Но я учту это

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +Микросервис выставления заявки от Facade через gRPC получает сообщение с Id заявки, Id пользователя, который собирается выставить заявку,
Мы не можем генерировать ID заявки на стороне фасада. это делает СУБД создавая уникальный ключ для объекта. 
Даже если мы бы делали его на фасаде. То есть вероятность колизий. в СУБД же придуман механизм избегания коллизий ключа.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +Микросервис выставления заявки от Facade через gRPC получает сообщение с Id заявки, Id пользователя, который собирается выставить заявку,
У нас система общения следующая. 
Если мы заводим данные, обновляем, редактируем. То мы идем через Kafka. 
Мы создаем событие открытия ордера. Оно может быть интересно не только этому микросервису.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +	USER_NOT_HAVE_MONEY = 7;
Я могу ошибаться, но enum не поддерживается в Grpc

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +  int32 quantity = 5;
https://docs.google.com/document/d/1JFq_g9cSWn0372pxw0ZwDewUuu7ypM6o/edit#heading=h.r6p7q1vsdrv2 
Требования, установить время жизни заявки.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +  int32 quantity = 5;
https://docs.google.com/document/d/1JFq_g9cSWn0372pxw0ZwDewUuu7ypM6o/edit#heading=h.ayxh9rn5x1ly
установить ограничение по обьему. Полагаю тут любой вариант подойдет, bool , или шаг количества.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +7. У пользователя недостаточно средств.
Идея отличная. Возможно стоит посмотреть в сторону кода ответа из http протокола. И сделать небольшой аналог.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +Микросервис выставления заявки от Facade через gRPC получает сообщение с Id заявки, Id пользователя, который собирается выставить заявку,
Вижу используется много проверок и обратной связи с формированием ошибок. 
Чтобы избежать ошибок обработки и сделать первичную валидацию. 
Предлагаю вариант когда тот же Facade идет в этот микросервис, по Grpc, проверяет все что хочет. Ему тут же могут прийти коды ответов, а это нужно определить отдельные сервисы в протофайле. 
И только потом, если все нормально, он идет в kafka и формирует событие, на создание заявки. Событие в любом случаи нам нужно.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +```
Я бы сказал, что было бы удобнее, если бы их разделяли по сервисам, допустим там где то сервис валидации, там будет GRPC, 
В отдельном месте у нас kafka. 
Методы путаются и трудно уследить кто чей.

2022-07-25 14:43 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +7. У пользователя недостаточно средств.
Update. переделка в сторону варианта ответа на запрос GRPC классом. Будет выглядеть лучше. условного Bool достаточно.

2022-07-25 15:08 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +	USER_NOT_HAVE_MONEY = 7;
https://docs.microsoft.com/ru-ru/dotnet/architecture/grpc-for-wcf-developers/protobuf-enums

2022-07-25 19:22 UTC, stictt commented on docs/adr/OrderMechanism/ADR.md
> +	USER_NOT_HAVE_MONEY = 7;
Проверил сериализацию и десериализацию на кафке. Все работает. Проблем не должно быть.

2022-07-29 11:12 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Микросервис выставления заявки от Facade через gRPC получает сообщение с Id заявки, Id пользователя, который собирается выставить заявку,
На счет id заявки:

да, верно. Стоит исправить

На счет системы общение:

Разве у нас так? Я думал, что между Facade и микросервисами - gRPC. Между микросервисами - Apache Kafka.

2022-07-29 18:36 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Микросервис выставления заявки от Facade через gRPC получает сообщение с Id заявки, Id пользователя, который собирается выставить заявку,
А насколько правильно использовать Facade для этих целей? Я всегда относился к Facade, как к интерфейсу

2022-07-29 21:15 UTC, ted7007 commented on docs/adr/OrderMechanism/ADR.md
> +Доработаю этот процесс.
Понимаю что это ещё все сыро, просто хочу подметить:
Что стоит законнектить этот процесс с микросервисом транзакций, я думаю не правильно что микросервис заявок сам будет ходить с запросами к балансу и портфелю?  
Ну и можем как-нибудь вместе подумать про алгоритм задачи "берет заявку покупки и сравнивает с заявкой продажи"

2022-07-30 05:40 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Доработаю этот процесс.
да, это лучше обсудить

2022-08-01 10:56 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +  int32 quantity = 5;
Это для других ADR

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +    "user_id" : "d28e5a67-8da4-4b76-97ce-1a648705c6e8",
Советую хранить плоский список заявок и сделать индекс по userId. Индекс даст возможность эффективно находить заявки конкрентного пользователя. В предложенной схеме сложно искать заявки по произвольному правилу

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +   Sell_order = 1;
Все поля enum всегда в UPPER_CASE (для всех прото)

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +message OrderCreatedEventRequest {
```suggestion
message OrderCreatedEvent {

```
Request лишнее, это просто событие, request это команда

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +enum OrderTypes {
```suggestion
enum OrderType {

```

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +message OrdersClosedEventRequest {
```suggestion
message OrdersClosedEvent {

```

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +   Order from = 1;
Мы стартуем транзакцию, при это событие назвается Closed. Тут стоит подумать над названием. OrderCandidateOccurred, например

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +   Order from = 1;
Чтобы ответить, сервису транзакций придётся хранить эти сущности. Что ведёт к задвоению данных и потенциальному рассинхрону. Основное правило - не следует допускать, чтобы чужие для сущности сервисы хранили сущность. Ещё непонятно как отличить дублирующее событие с одинаковыми данными

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +\- Создание заявки. Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросерв
Если лежит в базе, то в какой момент она может опять попасть в кандидаты для сделки?

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +      "inactive" : [
В mongo есть ограничение на размер документа. Можем получить переполнение

2022-08-01 13:58 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +\- Создание заявки. Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросерв
Что происходит с заявками, когда совершается транзакция? Как гарантируется, что заявка не попадёт в другую транзакцию? Или в тексте нужно описать, почему мы этого не боимся

2022-08-01 14:18 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +    "user_id" : "d28e5a67-8da4-4b76-97ce-1a648705c6e8",
Коллекция активных заявок:
```
{
   "user_id" : "0c870864-6b67-4f2e-8603-f1c716e6852b",
   "order_id" : "914b81de-9888-4200-a816-293b57d8cbdf"
},
{
   "user_id" : "0c870864-6b67-4f2e-8603-f1c716e6852b",
   "order_id" : "2e7b0815-5af1-4b12-8e11-9c540991147e"
},
```

Хранить в подобном виде?

2022-08-01 14:20 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +    "user_id" : "d28e5a67-8da4-4b76-97ce-1a648705c6e8",
Либо же

```
[0c870864-6b67-4f2e-8603-f1c716e6852b]
{
               "order_id" : "91d6bbdf-6388-4da9-9991-9c92e8b751f7",
            "type" : 1,
            "product_id" : "b5a7c6d8-3533-4d45-97ba-500f202b9077",
            "quantity" : 3232,
            "price" : 123.00,
},
```

2022-08-01 14:24 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +   Sell_order = 1;
исправлю.

2022-08-01 14:51 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +   Order from = 1;
тогда отправить GUID и ждать его

2022-08-02 07:45 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +\- Создание заявки. Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросерв
предполагаю, что можно использовать IHostedService и запускать фоновую задачу для обработки бд каждый раз, когда создается новая заявка и искать подходящие.

Проблема:
Нашлись подходящие заявки ( B1 и B2 ), данные отправлены в микросервис транзакций, микросервис транзакций начинает выполнять свои операции. В этот момент фоновый процесс для заявок решил закрыть заявку B1 ( которая в данный момент находится в транзакции ) заявкой B3. 

Вариант исхода:
Заявки B1 и B2 закроются раньше, поэтому транзакция с заявками B1 и B3 отменится.

Решение: 
Ввести маркер, который указывает, что заявка находится в транзакции и обрабатывать не нужно.

2022-08-03 04:02 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +\- Создание заявки. Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросерв
Любой фоновый процесс можно заменить на логику событий. У нас могут быть такие варианты:
* получили заявку
* нашли встречного кандидата (если не нашли, то просто в базу)
* запустили транзакцию
* получили событие неудачи
* пробуем заново найти двух лучших кандидатов
Выглядит, что не нужен фоновый процесс

2022-08-03 04:02 UTC, kazurus commented on docs/adr/OrderMechanism/ADR.md
> +message OrderCandidateOccurredEventResponse {
Нужно разделить на два события. Например OrderCandidateProcessFailed/OrderCandidateProcessAborted/OrderCandidateProcessSuccess

2022-08-04 13:59 UTC, kazurus reviewed
Дорабатываем с учётом встречи

2022-08-11 09:32 UTC, kazurus approved these changes

2022-08-11 09:37 UTC, Calabonga requested changes

2022-08-11 09:37 UTC, Calabonga commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
Что это такое "первичная валидация"?
На каком основании должен делать первичную валидацию? Вы хотите бизнес логику притащить на Facade?

2022-08-11 10:23 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
переделаю. Мк заявок будет через кафку отправлять сообщения в мк баланса, мк портфеля

2022-08-11 10:25 UTC, Calabonga commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
что есть "мк"?

2022-08-11 10:33 UTC, Calabonga commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
Ставлю approve с условием, что дублирование кода будет удалено

2022-08-11 10:33 UTC, Calabonga approved these changes

2022-08-11 11:34 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
> что есть "мк"?

микросервис

2022-08-11 13:02 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
> Ставлю approve с условием, что дублирование кода будет удалено

а какое дублирование?

2022-08-11 13:12 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
Если речь о


```proto
// Ответ от микросервиса транзакций
message OrderCandidateOccurredProcessFailed {
   string order_id = 1;
   string order_id_seller = 2;
}
```

```proto
// Ответ от микросервиса транзакций
message OrderCandidateProcessSuccess {
   string order_id = 1;
   string order_id_seller = 2;
}
```
, то я так сделал по совету A. Kazurus, вроде

2022-08-11 13:13 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
Если речь о 

```proto
// Ответ от микросервиса транзакций
message OrderCandidateOccurredProcessFailed {
   string order_id = 1;
   string order_id_seller = 2;
}
```

```proto
// Ответ от микросервиса транзакций
message OrderCandidateProcessSuccess {
   string order_id = 1;
   string order_id_seller = 2;
}
```
то это я сделал по совету A. Kazurus

2022-08-11 13:15 UTC, paradoxubivaet commented on docs/adr/OrderMechanism/ADR.md
> +Facade делает первичную валидацию, что заявку выставить возможно, после чего отправляет сообщение в Микросервис. На основе данных формируется заявка и сохраняется. Далее микросервис ищет подходящие з
а если речь о 

```
// В качестве индекса UserID
[6bf280fe-fa36-4fde-a69e-434cc76d45ae] 
{
   "in_transaction" : false,
   "order_id" : "6ff5a871-1008-414d-9803-5a8f7fb8ac31",
}
```
Коллекция активных заявок на продажу:

```
// В качестве индекса UserID:
[6bf280fe-fa36-4fde-a69e-434cc76d45ae]
{
   "in_transaction" : true,
   "order_id" : "b0f2e904-962f-493c-9b2e-87fd270e2e11"
}
```

то это две коллекции. Для активных заявок продажи и покупки. Я сначала хотел хранить все активные заявки в одной коллекции, но тогда бы поиск подходящей заявки был бы не очень удобен

2025-12-11 03:57 UTC, closed without merging