Facade
FizzyShow/markershtern pull request #9
Opened 2022-07-18 10:45 UTC by stictt

2022-07-19 12:14 UTC, FizzyShow commented
Как-то много файлов, которые генерируются автоматом (по типу папки .vs, и файлов *.cache)

2022-07-20 08:20 UTC, stictt commented on Facade/Facade/Facade/obj/Facade.csproj.nuget.dgspec.json
> -            },
А зачем удалять провайдер Kafka ? 
Без него ж не работает.

2022-07-24 16:42 UTC, ted7007 reviewed
Как упомянули выше стоит убрать файлы с vs
Больше комментариев нет

2022-07-24 16:42 UTC, ted7007 commented on Facade/Facade/Facade/Protos/event.proto
> +package greet;
это здесь нужно от шаблона?

2022-07-24 16:42 UTC, ted7007 commented on Facade/Facade/Facade/Protos/greet.proto
> +package greet;
Также как и с event.proto

2022-07-24 16:42 UTC, ted7007 commented on Facade/Facade/Facade/Services/SubmitEventNewProduct.cs
> +        ProducerConfig _consumerConfig;
_producerConfig?

2022-07-24 16:45 UTC, ted7007 commented on Facade/Facade/Facade/Protos/greet.proto
> +service ProductService {
этот .proto обновился в adr "товары доступные для торговли".
после его approve стоит переписать

2022-07-25 13:38 UTC, stictt commented on Facade/Facade/Facade/Protos/greet.proto
> +package greet;
Тут заглушка пока не встанет другой микросервис.

2022-07-25 13:47 UTC, stictt commented on Facade/Facade/Facade/Protos/event.proto
> +package greet;
В том нейминге который есть, нет не нужен. Возьму на рефакторинг. 
неймспейс помогает с генератором классов. 
а package в файле конфигов указывает на наши протофайлы, и например их разделение на клиент/сервер

2022-08-11 08:48 UTC, ted7007 commented
Неправильно начали работать с задачами, вливали все в один pr. 
В дальнейшем под каждую задачу будем  создавать новый pr.

2022-08-11 09:40 UTC, nevrotkampot commented on Facade/Facade/Facade.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Элементы решения", "Элементы решения", "{71DA7F98-4F8C-445D-A434-6CAAFCDE2AB0}"
русских символов лучше избегать

2022-08-11 09:45 UTC, Calabonga requested changes

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/Briefcase/AddProduct.cs
> +        private string GetConnectionString()
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/Briefcase/GetListUserProducts.cs
> +        {
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/Briefcase/RemoveProduct.cs
> +        {
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/Briefcase/ValidateOrder.cs
> +        private string GetConnectionString()
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/GetListTradeProducts.cs
> +        private string GetConnectionString()
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/GetUserID.cs
> +        private string GetConnectionString()
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/OrderService.cs
> +        private string GetConnectionString()
Дублирование кода. А как же DRY?

2022-08-11 09:45 UTC, Calabonga commented on Facade/Facade/Facade/Services/UserBriefcaseService.cs
> +        private string GetConnectionString()
А если ConnectionString измениться??
А во всех файлах поменять не получится (забыл, не заметил, не нашел)?
Дублирование кода. А как же DRY?

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade.sln
> +	ProjectSection(SolutionItems) = preProject
эта секция здесь точно нужна?

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/GetUserID.cs
> +                //To DO log
такие вещи оставлять нельзя. либо бросать exception либо логировать

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Facade.csproj
> +    <PackageReference Include="AutoMapper" Version="11.0.1" />
не увидел логгера в проекте. ничего не логируется, хотя в настройках стоит UseSerilog.

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Protos/CustomTypes/DecimalValue.cs
> +            // throw new ArgumentException("decimal value is null");
почистить комменты

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/GetListTradeProducts.cs
> +                //To DO log
лучше просто бросать эксепшен чем просто промолчать

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/GetUserID.cs
> +            using (var channel = GrpcChannel.ForAddress(_connectionString))
не очень хорошая практика каждый раз создавать канал. см. https://docs.microsoft.com/ru-ru/aspnet/core/grpc/performance?view=aspnetcore-6.0

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/OrderService.cs
> +                //To DO log
тоже самое что и выше. + код везде дублируется, следует вынести его в отдельную сущность

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/SubmitEventNewProduct.cs
> +                    //To do log
бессмысленная конструкция с накладными расходами.

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/SubmitEventNewProduct.cs
> +                //To DO log
тоже самое

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/UserBriefcaseService.cs
> +        private string GetConnectionString()
вынести + Exception

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Startup.cs
> +            if (env.IsDevelopment())
незнаю как вы раскатываете, но в конфиг файлах у вас нет Production настроек.

2022-08-11 10:13 UTC, nevrotkampot commented on Protos/decimalValue.proto
> +option csharp_namespace = "CustomTypes";
стоит дать более осмысленный неймспейс. вместо customTypes назвать например Money. т.к. используется для денег в вашем контексте

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/GetUserID.cs
> +        public async Task<(bool isComplite, string userId, Exception exception)>
Iscomplete и Exception можно обьеденить. например получатель будет смотреть if (exception!=null) значит iscomplete = true и наоборот

2022-08-11 10:13 UTC, nevrotkampot commented on Facade/Facade/Facade/Services/GetUserID.cs
> +        private async Task<string> LoadDataAsync(string login, string password)
метод стоит переименовать в более осмысленный. например LoadUserIdByGrpc

2022-08-12 04:45 UTC, stictt commented on Facade/Facade/Facade/Services/UserBriefcaseService.cs
> +        private string GetConnectionString()
Он берет ConnectionString  из appsettings. Если он поменяется. То при перезапуске все это подтянут.

2022-08-12 04:57 UTC, stictt commented on Facade/Facade/Facade/Services/GetUserID.cs
> +        public async Task<(bool isComplite, string userId, Exception exception)>
isComplite сам по себе, при не выполнении, не всегда подразумевает ошибку. 
может быть не очевидность, isComplite = falsе, а Exception  = null. Ну либо по кортежу так может казаться. 

Переделаем на более стандартные варианты.

2022-08-14 16:29 UTC, ted7007 commented on Facade/Facade/Facade/Services/UserBriefcaseService.cs
> +        private string GetConnectionString()
т.к. была добавлена фабрика клиентов, необходимость в методе отпала

2022-08-15 06:33 UTC, ted7007 commented on Facade/Facade/Facade/Startup.cs
> +            if (env.IsDevelopment())
Могу я попросить немного более развернутый комментарий? В какой сторону двигаться не совсем понятно.
Основные настройки находятся в asppsettings(строки подключения), они остаются те же.
Или это намек на то, что стоит например реализовать ExceptionHandler для production среды?

2022-08-15 06:40 UTC, Calabonga commented on Facade/Facade/Facade/Facade.csproj
> +    <TargetFramework>net5.0</TargetFramework>
Net6 ?

2022-08-15 06:42 UTC, Calabonga commented on Facade/Facade/Facade/GrpcServices/GrpcOrderService.cs
> +            Order.CreateOrderResponse response =
Mapper надо в конструктор вливать IMapper.
От статики надо избавляться

2022-08-15 06:44 UTC, Calabonga commented on Facade/Facade/Facade/GrpcServices/GrpcOrderService.cs
> +            var mappedResponse = Mapper.Map<Order.CreateOrderResponse, CreateOrderResponse>(response);
IMapper в конструктор

2022-08-15 06:45 UTC, Calabonga commented on Facade/Facade/Facade/GrpcServices/GrpcProductService.cs
> +            var mappedRequest = Mapper.Map<ProductClient.GetProductsRequest, Product.GetProductsRequest>(request);
Маппер конструктор везде надо

2022-08-15 06:45 UTC, Calabonga commented on Facade/Facade/Facade/Mapper.cs
> +        public static TOut Map<TIn, TOut>(TIn valueToConvert)
Статика не нужна. Есть IMapper

2022-08-15 06:47 UTC, Calabonga commented on Facade/Facade/Facade/Services/UserBriefcaseService.cs
> +                var reply = await _client.GetUserProductsAsync(request);
А если ответ будет null?

2022-08-15 07:16 UTC, Calabonga approved these changes

2022-08-15 16:35 UTC, merged